version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: RO.DevTest.WebApi/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=oficinasdb;Username=admin;Password=admin123
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: oficinas-postgres
    environment:
      POSTGRES_DB: oficinasdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
