# Etapa 1 - Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copia csproj e restaura dependências
COPY *.sln .
COPY RO.DevTest.Application/RO.DevTest.Application.csproj ./RO.DevTest.Application/
COPY RO.DevTest.Domain/RO.DevTest.Domain.csproj ./RO.DevTest.Domain/
COPY RO.DevTest.Persistence/RO.DevTest.Persistence.csproj ./RO.DevTest.Persistence/
COPY RO.DevTest.Infrastructure/RO.DevTest.Infrastructure.csproj ./RO.DevTest.Infrastructure/
COPY RO.DevTest.WebApi/RO.DevTest.WebApi.csproj ./RO.DevTest.WebApi/

RUN dotnet restore RO.DevTest.WebApi/RO.DevTest.WebApi.csproj

# Copia tudo
COPY . .

# Publica o app
WORKDIR /app/RO.DevTest.WebApi
RUN dotnet publish -c Release -o out

# Etapa 2 - Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/RO.DevTest.WebApi/out .

ENTRYPOINT ["dotnet", "RO.DevTest.WebApi.dll"]